export const COUNTRY = 'SET_COUNTRY'
export const PLAYER_VERSION = 'SET_PLAYER_VERSION'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_OK = 'LOGIN_OK'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const KEEP_ALIVE_REQUEST = 'KEEP_ALIVE_REQUEST'
export const KEEP_ALIVE_OK = 'KEEP_ALIVE_OK'
export const KEEP_ALIVE_FAIL = 'KEEP_ALIVE_FAIL'

export const SET_FROM_TIMESTAMP = 'SET_FROM_TIMESTAMP'
export const SET_TO_TIMESTAMP = 'SET_TO_TIMESTAMP'

export const CHANNELS_REQUEST = 'CHANNELS_REQUEST'
export const CHANNELS_OK = 'CHANNELS_OK'
export const CHANNELS_FAIL = 'CHANNELS_FAIL'
export const LOWER_CHANNEL = 'LOWER_CHANNEL'
export const HIGHER_CHANNEL = 'HIGHER_CHANNEL'

export const PROGRAMS_REQUEST = 'PROGRAMS_REQUEST'
export const PROGRAMS_OK = 'PROGRAMS_OK'
export const PROGRAMS_FAIL = 'PROGRAMS_FAIL'

export const PROGRAM_REMINDER = 'SET_REMINDER'

export const CHANGE_PLAYER_CHANNEL = 'CHANGE_PLAYER_CHANNEL'
export const CHANGE_PLAYER_URL = 'CHANGE_PLAYER_URL'

export const VIDEO_PLAYER = 'SET_VIDEO_PLAYER'

export const IS_MOBILE = 'SET_IS_MOBILE'
